### PR TITLE
unexpected tokens. (fix)

### PR DESCRIPTION
**Pull request by Lisias**
Yeah. More lint. :)

### CODE REVIEW

**Comment by Lisias** [comment]
Hi!

How do I fix this pull request?

**Comment by ChrisAdderley** [comment]
Please target all PRs to dev.

**Comment by Lisias** [comment]
But it already is!!

Screen Shot 2020-07-26 at 17 55 15

**Comment by ChrisAdderley** [comment]
Well, your initial request was to master, which is why the integration checks ran, and why they failed. I'll merge this now as it looks fine.

**Comment by Lisias** [comment]
Now I got it. Adding a new commit would trick travis to recheck the pullrequest, or once travis rejects it, it's tainted for good and only a new pullrequest would solve the issue?

**Comment by ChrisAdderley** [comment]
Not quite. The Travis checks I have are only release level checks. They only run when a PR is targeted to master (which is the release branch). You targeted this to master, so it ran the release checks... which failed, because the version number has not been updated, etc. 

Merging to dev does not run any checks at the moment, so everything is fine.

**Pull request merged**
